config-version: 2
name: 'stripe'
version: '1.0.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  stripe:
    +schema: stripe
    +materialized: table
    intermediate:
      +materialized: table
    staging:
      +materialized: table
      +schema: stg_stripe
      tmp:
        +materialized: view

vars:
  stripe:
    account: "{{ source('stripe', 'account') }}"
    balance_transaction: "{{ source('stripe', 'balance_transaction') }}"
    card: "{{ source('stripe', 'card') }}"
    charge: "{{ source('stripe', 'charge') }}"
    customer: "{{ source('stripe', 'customer') }}"
    dispute: "{{ source('stripe', 'dispute') }}"
    discount: "{{ source('stripe', 'discount') }}"
    fee: "{{ source('stripe', 'fee') }}"
    invoice: "{{ source('stripe', 'invoice') }}"
    invoice_line_item: "{{ source('stripe', 'invoice_line_item') }}"
    payment_intent: "{{ source('stripe', 'payment_intent') }}"
    payment_method_card: "{{ source('stripe', 'payment_method_card') }}"
    payment_method: "{{ source('stripe', 'payment_method') }}"
    payout: "{{ source('stripe', 'payout') }}"
    payout_balance_transaction: "{{ source('stripe', 'payout_balance_transaction') }}"
    price_plan: "{{ source('stripe', 'price_plan') }}"
    product: "{{ source('stripe', 'product') }}"
    refund: "{{ source('stripe', 'refund') }}"
    subscription: "{{ source('stripe', 'subscription') }}"
    transfer: "{{ source('stripe', 'transfer') }}"

    card_pass_through_columns: []
