config-version: 2
name: 'stripe'

version: '0.10.2'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  stripe:
    +schema: stripe
    +materialized: table
    intermediate:
      +materialized: table
vars:
  stripe:
    account: "{{ ref('stg_stripe__account') }}"
    balance_transaction: "{{ ref('stg_stripe__balance_transaction') }}"
    card: "{{ ref('stg_stripe__card') }}"
    charge: "{{ ref('stg_stripe__charge') }}"
    customer: "{{ ref('stg_stripe__customer') }}"
    fee: "{{ ref('stg_stripe__fee') }}"
    invoice: "{{ ref('stg_stripe__invoice') }}"
    invoice_line_item: "{{ ref('stg_stripe__invoice_line_item') }}"
    payment_intent: "{{ ref('stg_stripe__payment_intent') }}"
    payment_method_card: "{{ ref('stg_stripe__payment_method_card') }}"
    payment_method: "{{ ref('stg_stripe__payment_method') }}"
    payout: "{{ ref('stg_stripe__payout') }}"
    price_plan: "{{ ref('stg_stripe__price_plan') }}"
    refund: "{{ ref('stg_stripe__refund') }}"
    subscription: "{{ ref('stg_stripe__subscription') }}"
