{% macro get_charge_columns() %}

{% set columns = [
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "amount", "datatype": dbt.type_int()},
    {"name": "amount_refunded", "datatype": dbt.type_int()},
    {"name": "application", "datatype": dbt.type_string()},
    {"name": "application_fee_amount", "datatype": dbt.type_int()},
    {"name": "balance_transaction_id", "datatype": dbt.type_string()},
    {"name": "bank_account_id", "datatype": dbt.type_string()},
    {"name": "calculated_statement_descriptor", "datatype": dbt.type_string()},
    {"name": "captured", "datatype": "boolean"},
    {"name": "card_id", "datatype": dbt.type_string()},
    {"name": "connected_account_id", "datatype": dbt.type_string()},
    {"name": "created", "datatype": dbt.type_timestamp()},
    {"name": "currency", "datatype": dbt.type_string()},
    {"name": "customer_id", "datatype": dbt.type_string()},
    {"name": "description", "datatype": dbt.type_string()},
    {"name": "destination", "datatype": dbt.type_string()},
    {"name": "failure_code", "datatype": dbt.type_string()},
    {"name": "failure_message", "datatype": dbt.type_string()},
    {"name": "fraud_details_stripe_report", "datatype": dbt.type_string()},
    {"name": "fraud_details_user_report", "datatype": dbt.type_string()},
    {"name": "id", "datatype": dbt.type_string()},
    {"name": "invoice_id", "datatype": dbt.type_string()},
    {"name": "livemode", "datatype": "boolean"},
    {"name": "metadata", "datatype": dbt.type_string()},
    {"name": "on_behalf_of", "datatype": dbt.type_string()},
    {"name": "outcome_network_status", "datatype": dbt.type_string()},
    {"name": "outcome_reason", "datatype": dbt.type_string()},
    {"name": "outcome_risk_level", "datatype": dbt.type_string()},
    {"name": "outcome_risk_score", "datatype": dbt.type_int()},
    {"name": "outcome_seller_message", "datatype": dbt.type_string()},
    {"name": "outcome_type", "datatype": dbt.type_string()},
    {"name": "paid", "datatype": "boolean"},
    {"name": "payment_intent_id", "datatype": dbt.type_string()},
    {"name": "payment_method_id", "datatype": dbt.type_string()},
    {"name": "receipt_email", "datatype": dbt.type_string()},
    {"name": "receipt_number", "datatype": dbt.type_string()},
    {"name": "receipt_url", "datatype": dbt.type_string()},
    {"name": "refunded", "datatype": "boolean"},
    {"name": "shipping_address_city", "datatype": dbt.type_string()},
    {"name": "shipping_address_country", "datatype": dbt.type_string()},
    {"name": "shipping_address_line_1", "datatype": dbt.type_string()},
    {"name": "shipping_address_line_2", "datatype": dbt.type_string()},
    {"name": "shipping_address_postal_code", "datatype": dbt.type_string()},
    {"name": "shipping_address_state", "datatype": dbt.type_string()},
    {"name": "shipping_carrier", "datatype": dbt.type_string()},
    {"name": "shipping_name", "datatype": dbt.type_string()},
    {"name": "shipping_phone", "datatype": dbt.type_string()},
    {"name": "shipping_tracking_number", "datatype": dbt.type_string()},
    {"name": "source_id", "datatype": dbt.type_string()},
    {"name": "source_transfer", "datatype": dbt.type_string()},
    {"name": "statement_descriptor", "datatype": dbt.type_string()},
    {"name": "status", "datatype": dbt.type_string()},
    {"name": "transfer_data_destination", "datatype": dbt.type_string()},
    {"name": "transfer_group", "datatype": dbt.type_string()},
    {"name": "transfer_id", "datatype": dbt.type_string()},
    {"name": "billing_detail_address_city", "datatype": dbt.type_string()},
    {"name": "billing_detail_address_country", "datatype": dbt.type_string()},
    {"name": "billing_detail_address_line1", "datatype": dbt.type_string()},
    {"name": "billing_detail_address_line2", "datatype": dbt.type_string()},
    {"name": "billing_detail_address_postal_code", "datatype": dbt.type_string()},
    {"name": "billing_detail_address_state", "datatype": dbt.type_string()},
    {"name": "billing_detail_email", "datatype": dbt.type_string()},
    {"name": "billing_detail_name", "datatype": dbt.type_string()},
    {"name": "billing_detail_phone", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}
