config-version: 2

name: 'stripe_integration_tests'
version: '1.5.0'

profile: 'integration_tests'

# For use with validations
models:
  +schema: "stripe_{{ var('directed_schema','dev') }}"

vars:
  # enable when generating docs
  # stripe__using_credit_notes: true # @docs-include

  stripe_schema: stripe_integrations_tests
  stripe:
    stripe_account_identifier: "account_data"
    stripe_group_identifier: "group_data"
    stripe_balance_transaction_identifier: "balance_transaction_data"
    stripe_card_identifier: "card_data"
    stripe_charge_identifier: "charge_data"
    stripe_customer_identifier: "customer_data"
    stripe_discount_identifier: "discount_data"
    stripe_dispute_identifier: "dispute_data"
    stripe_fee_identifier: "fee_data"
    stripe_invoice_identifier: "invoice_data"
    stripe_invoice_line_item_identifier: "invoice_line_item_data"
    stripe_payment_intent_identifier: "payment_intent_data"
    stripe_payment_method_card_identifier: "payment_method_card_data"
    stripe_payment_method_identifier: "payment_method_data"
    stripe_payout_identifier: "payout_data"
    stripe_payout_balance_transaction_identifier: "payout_balance_transaction_data"
    stripe_plan_identifier: "plan_data"
    stripe_price_identifier: "price_data"
    stripe_product_identifier: "product_data"
    stripe_refund_identifier: "refund_data"
    stripe_subscription_history_identifier: "subscription_history_data"
    stripe_subscription_identifier: "subscription_data"
    stripe_subscription_item_identifier: "subscription_item_data"
    stripe_transfer_identifier: "transfer_data"
    stripe_credit_note_identifier: "credit_note_data"
    stripe_credit_note_line_item_identifier: "credit_note_line_item_data"


seeds:
  +docs:
    show: False
  stripe_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"
    +column_types:
      _fivetran_synced: timestamp
      created: timestamp
      canceled_at: timestamp
      voided_at: timestamp
      invoice_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
      end: timestamp
    balance_transaction_data:
      +column_types:
        available_on: timestamp
    coupon_data:
      +column_types:
        created: timestamp
        redeem_by: timestamp
        _fivetran_synced: timestamp
    charge_data:
      +column_types:
        balance_transaction_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        created: timestamp
        captured: boolean
        livemode: boolean
        paid: boolean
        refunded: boolean
        amount: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        amount_refunded: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        application_fee_amount: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        outcome_risk_score: "{{ 'float' if target.type in ('redshift','postgres') else 'FLOAT64' if target.type == 'bigquery' else 'float'}}"
    customer_data:
      +column_types:
        description: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
    invoice_data:
      +column_types:
        due_date: timestamp
        paid: boolean
        auto_advance: boolean
        amount_due: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        amount_paid: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        amount_remaining: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        subtotal: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        tax: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        total: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        attempt_count: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        number: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        post_payment_credit_notes_amount: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
        pre_payment_credit_notes_amount: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"
    payout_data:
      +column_types:
        destination_bank_account_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        destination_card_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
    price_data:
      +column_types:
        recurring_interval: "{{ 'varchar(100)' if target.type in ('redshift','postgres') else 'string'}}"
        recurring_aggregate_usage: "{{ 'varchar(100)' if target.type in ('redshift','postgres') else 'string'}}"
        recurring_usage_type: "{{ 'varchar(100)' if target.type in ('redshift','postgres') else 'string'}}"
    discount_data:
      +enabled: "{{ true if target.type not in ('snowflake', 'postgres') else false }}"
      +column_types:
        amount: bigint
    discount_data_snowflake:
      +alias: discount_data
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
    discount_data_postgres:
      +alias: discount_data
      +enabled: "{{ true if target.type == 'postgres' else false }}"
      +column_types:
        amount: "{{ 'bigint' if target.type in ('redshift','postgres') else 'INT64' if target.type == 'bigquery' else 'bigint'}}"


dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

flags:
  send_anonymous_usage_stats: False

  use_colors: True 