version: 2

sources:
  - name: dbt_stripe_account_src
    tables:
      - name: customer
      - name: invoice
      - name: subscription_history 

  - name: ft_netbox_public
    tables:
      - name: dcim_site
      - name: dcim_device  