version: 2

sources:
  - name: dbt_stripe_account_src
    tables:
      - name: customer
      - name: invoice
      - name: subscription_history 
      - name: product
      - name: invoice_line_item
      - name: price
      - name: plan
      - name: product_classes

  - name: ft_netbox_public
    tables:
      - name: dcim_site
      - name: dcim_device  
      - name: dcim_region 
    
  - name: dbt_netbox
    tables:
      - name: regions_locations
      - name: device_subscription_item_history